export const DILLER_LIST = [
  { kod: "tr", etiket: "🇹🇷 TR", href: "/" },
  { kod: "en", etiket: "🇬🇧 EN", href: "/en" },
  { kod: "ru", etiket: "🇷🇺 RU", href: "/ru" },
  { kod: "ar", etiket: "🇸🇦 AR", href: "/ar" },
  { kod: "fa", etiket: "🇮🇷 FA", href: "/fa" },
];

export const CEVIRILER = {
  tr: {
    dir: "ltr",
    hero1: "Doğru Hekime",
    hero2: "Güvenle Ulaş",
    hero_alt: "Doğrulanmış yorumlar, şeffaf profiller ve kolay randevu.",
    uzmanlik_baslik: "Uzmanlık Alanı Seçin",
    uzmanlik_alt: "İhtiyacınıza göre doğru uzmana ulaşın",
    uzmanliklar: { "kbb-uzmani": "KBB", "kardiyoloji": "Kardiyoloji", "ortopedi": "Ortopedi", "plastik-cerrahi": "Plastik Cerrahi", "goz-hastaliklari": "Göz", "dis-hekimi": "Diş Hekimi", "dermatoloji": "Dermatoloji", "noroloji": "Nöroloji", "psikiyatri": "Psikiyatri", "cocuk-hastaliklari": "Çocuk Sağlığı", "estetik-cerrahi": "Estetik Cerrahi", "rinoplasti": "Rinoplasti" },
    nasil_baslik: "Nasıl Çalışır?",
    adimlar: [
      { baslik: "Doktor Ara", aciklama: "Uzmanlık ve şehir seçerek yüzlerce doktor arasından filtrele" },
      { baslik: "Profil İncele", aciklama: "Doğrulanmış yorumlar ve şeffaf bilgileri gör" },
      { baslik: "Randevu Al", aciklama: "Doktor profilinden direkt randevu talebi gönder" },
    ],
    fiyat_baslik: "Paketler & Fiyatlar",
    fiyat_alt: "Sağlık profesyonelleri için şeffaf fiyatlandırma",
    paketler: [
      { ad: "Ücretsiz", fiyat: "₺0", periyot: "sonsuza dek", renk: "#6B7280", bg: "#F5F7FA", border: "#E5E7EB", ozellikler: ["Temel profil", "Randevu talebi", "Hasta yorumları", "Fotoğraf yükleme"], cta: "Ücretsiz Başla", href: "/kayit-ol", populer: false },
      { ad: "Premium", fiyat: "₺999", periyot: "ay", renk: "#D97706", bg: "#FFFBEB", border: "#FDE68A", ozellikler: ["Temel profil", "Randevu talebi", "Hasta yorumları", "AI Asistan", "WhatsApp entegrasyonu"], cta: "Premium'a Geç", href: "mailto:satis@doktorpusula.com", populer: true },
      { ad: "Pro", fiyat: "₺1.599", periyot: "ay", renk: "#7C3AED", bg: "#F5F3FF", border: "#DDD6FE", ozellikler: ["Tüm Premium özellikler", "Analitik dashboard", "Öne çıkarma", "Medya / Makale yayını"], cta: "Pro'ya Geç", href: "mailto:satis@doktorpusula.com", populer: false },
    ],
    neden_baslik: "Neden DoktorPusula?",
    neden: [
      { ikon: "✅", baslik: "Doğrulanmış Yorumlar", aciklama: "Her yorum telefon numarasıyla doğrulanır, silinemez" },
      { ikon: "🇹🇷", baslik: "Tamamen Yerli", aciklama: "Yabancı sermayeden bağımsız, Türk doktorların güvendiği" },
      { ikon: "🌍", baslik: "Çok Dilli Destek", aciklama: "TR · EN · RU · AR · FA dillerinde tam destek" },
    ],
    cta_baslik: "Profilinizi Oluşturun",
    cta_alt: "Ücretsiz profilinizi oluşturun ve daha fazla hastaya ulaşın.",
    cta_btn: "Ücretsiz Kayıt Ol",
    kayit: "Kayıt Ol",
    giris: "Giriş Yap",
    populer: "Popüler",
  },

  en: {
    dir: "ltr",
    hero1: "Find the Right Doctor",
    hero2: "With Confidence",
    hero_alt: "Verified reviews, transparent profiles, and easy appointment booking.",
    uzmanlik_baslik: "Choose a Specialty",
    uzmanlik_alt: "Find the right specialist for your needs",
    uzmanliklar: { "kbb-uzmani": "ENT", "kardiyoloji": "Cardiology", "ortopedi": "Orthopedics", "plastik-cerrahi": "Plastic Surgery", "goz-hastaliklari": "Eye", "dis-hekimi": "Dentist", "dermatoloji": "Dermatology", "noroloji": "Neurology", "psikiyatri": "Psychiatry", "cocuk-hastaliklari": "Pediatrics", "estetik-cerrahi": "Aesthetic Surgery", "rinoplasti": "Rhinoplasty" },
    nasil_baslik: "How It Works",
    adimlar: [
      { baslik: "Search Doctors", aciklama: "Filter hundreds of doctors by specialty and city" },
      { baslik: "Review Profile", aciklama: "Read verified reviews and transparent information" },
      { baslik: "Book Appointment", aciklama: "Send an appointment request directly from the doctor profile" },
    ],
    fiyat_baslik: "Packages & Pricing",
    fiyat_alt: "Transparent pricing for healthcare professionals",
    paketler: [
      { ad: "Free", fiyat: "₺0", periyot: "forever", renk: "#6B7280", bg: "#F5F7FA", border: "#E5E7EB", ozellikler: ["Basic profile", "Appointment requests", "Patient reviews", "Photo upload"], cta: "Start Free", href: "/kayit-ol", populer: false },
      { ad: "Premium", fiyat: "₺999", periyot: "month", renk: "#D97706", bg: "#FFFBEB", border: "#FDE68A", ozellikler: ["Basic profile", "Appointment requests", "Patient reviews", "AI Assistant", "WhatsApp integration"], cta: "Go Premium", href: "mailto:satis@doktorpusula.com", populer: true },
      { ad: "Pro", fiyat: "₺1,599", periyot: "month", renk: "#7C3AED", bg: "#F5F3FF", border: "#DDD6FE", ozellikler: ["All Premium features", "Analytics dashboard", "Featured listing", "Media / Article publishing"], cta: "Go Pro", href: "mailto:satis@doktorpusula.com", populer: false },
    ],
    neden_baslik: "Why DoktorPusula?",
    neden: [
      { ikon: "✅", baslik: "Verified Reviews", aciklama: "Every review is authenticated by phone and cannot be deleted" },
      { ikon: "🇹🇷", baslik: "100% Independent", aciklama: "No foreign investment, trusted by Turkish doctors" },
      { ikon: "🌍", baslik: "Multilingual Support", aciklama: "Full support in TR · EN · RU · AR · FA" },
    ],
    cta_baslik: "Create Your Profile",
    cta_alt: "Build your free profile and reach more patients.",
    cta_btn: "Register Free",
    kayit: "Register Free",
    giris: "Login",
    populer: "Popular",
  },

  ru: {
    dir: "ltr",
    hero1: "Найдите Нужного Врача",
    hero2: "С Полной Уверенностью",
    hero_alt: "Подтверждённые отзывы, прозрачные профили и удобная запись на приём.",
    uzmanlik_baslik: "Выберите Специальность",
    uzmanlik_alt: "Найдите нужного специалиста",
    uzmanliklar: { "kbb-uzmani": "ЛОР", "kardiyoloji": "Кардиология", "ortopedi": "Ортопедия", "plastik-cerrahi": "Пластика", "goz-hastaliklari": "Офтальмология", "dis-hekimi": "Стоматология", "dermatoloji": "Дерматология", "noroloji": "Неврология", "psikiyatri": "Психиатрия", "cocuk-hastaliklari": "Педиатрия", "estetik-cerrahi": "Эстетика", "rinoplasti": "Ринопластика" },
    nasil_baslik: "Как Это Работает",
    adimlar: [
      { baslik: "Найти Врача", aciklama: "Фильтруйте сотни врачей по специальности и городу" },
      { baslik: "Изучить Профиль", aciklama: "Читайте подтверждённые отзывы и прозрачную информацию" },
      { baslik: "Записаться", aciklama: "Отправьте запрос на приём прямо из профиля врача" },
    ],
    fiyat_baslik: "Тарифы и Цены",
    fiyat_alt: "Прозрачные тарифы для медицинских специалистов",
    paketler: [
      { ad: "Бесплатно", fiyat: "₺0", periyot: "навсегда", renk: "#6B7280", bg: "#F5F7FA", border: "#E5E7EB", ozellikler: ["Базовый профиль", "Запись на приём", "Отзывы пациентов", "Загрузка фото"], cta: "Начать бесплатно", href: "/kayit-ol", populer: false },
      { ad: "Премиум", fiyat: "₺999", periyot: "месяц", renk: "#D97706", bg: "#FFFBEB", border: "#FDE68A", ozellikler: ["Базовый профиль", "Запись на приём", "Отзывы пациентов", "ИИ Ассистент", "WhatsApp интеграция"], cta: "Перейти на Премиум", href: "mailto:satis@doktorpusula.com", populer: true },
      { ad: "Про", fiyat: "₺1 599", periyot: "месяц", renk: "#7C3AED", bg: "#F5F3FF", border: "#DDD6FE", ozellikler: ["Всё из Премиум", "Аналитика", "Продвижение профиля", "Публикация статей"], cta: "Перейти на Про", href: "mailto:satis@doktorpusula.com", populer: false },
    ],
    neden_baslik: "Почему DoktorPusula?",
    neden: [
      { ikon: "✅", baslik: "Подтверждённые Отзывы", aciklama: "Каждый отзыв подтверждается по телефону и не может быть удалён" },
      { ikon: "🇹🇷", baslik: "Полностью Независимый", aciklama: "Без иностранных инвестиций, доверяют турецкие врачи" },
      { ikon: "🌍", baslik: "Многоязычная Поддержка", aciklama: "Полная поддержка на TR · EN · RU · AR · FA" },
    ],
    cta_baslik: "Создайте Ваш Профиль",
    cta_alt: "Создайте бесплатный профиль и привлекайте больше пациентов.",
    cta_btn: "Зарегистрироваться",
    kayit: "Регистрация",
    giris: "Войти",
    populer: "Популярный",
  },

  ar: {
    dir: "rtl",
    hero1: "ابحث عن الطبيب المناسب",
    hero2: "بكل ثقة",
    hero_alt: "تقييمات موثقة، ملفات شخصية شفافة، وحجز مواعيد سهل.",
    uzmanlik_baslik: "اختر التخصص",
    uzmanlik_alt: "ابحث عن المتخصص المناسب لاحتياجاتك",
    uzmanliklar: { "kbb-uzmani": "أنف وأذن وحنجرة", "kardiyoloji": "قلبية", "ortopedi": "عظام", "plastik-cerrahi": "تجميل", "goz-hastaliklari": "عيون", "dis-hekimi": "أسنان", "dermatoloji": "جلدية", "noroloji": "أعصاب", "psikiyatri": "نفسية", "cocuk-hastaliklari": "أطفال", "estetik-cerrahi": "تجميل", "rinoplasti": "تجميل الأنف" },
    nasil_baslik: "كيف يعمل",
    adimlar: [
      { baslik: "ابحث عن طبيب", aciklama: "تصفية مئات الأطباء حسب التخصص والمدينة" },
      { baslik: "راجع الملف الشخصي", aciklama: "اقرأ التقييمات الموثقة والمعلومات الشفافة" },
      { baslik: "احجز موعدًا", aciklama: "أرسل طلب موعد مباشرة من ملف الطبيب" },
    ],
    fiyat_baslik: "الباقات والأسعار",
    fiyat_alt: "أسعار شفافة للمتخصصين في الرعاية الصحية",
    paketler: [
      { ad: "مجاني", fiyat: "₺0", periyot: "للأبد", renk: "#6B7280", bg: "#F5F7FA", border: "#E5E7EB", ozellikler: ["ملف شخصي أساسي", "طلبات المواعيد", "تقييمات المرضى", "رفع الصور"], cta: "ابدأ مجانًا", href: "/kayit-ol", populer: false },
      { ad: "بريميوم", fiyat: "₺999", periyot: "شهر", renk: "#D97706", bg: "#FFFBEB", border: "#FDE68A", ozellikler: ["ملف أساسي", "طلبات المواعيد", "تقييمات", "مساعد ذكاء اصطناعي", "واتساب"], cta: "ترقية إلى بريميوم", href: "mailto:satis@doktorpusula.com", populer: true },
      { ad: "برو", fiyat: "₺1,599", periyot: "شهر", renk: "#7C3AED", bg: "#F5F3FF", border: "#DDD6FE", ozellikler: ["كل مزايا بريميوم", "لوحة تحليلات", "إبراز الملف", "نشر المقالات"], cta: "ترقية إلى برو", href: "mailto:satis@doktorpusula.com", populer: false },
    ],
    neden_baslik: "لماذا DoktorPusula؟",
    neden: [
      { ikon: "✅", baslik: "تقييمات موثقة", aciklama: "كل تقييم مؤكد بالهاتف ولا يمكن حذفه" },
      { ikon: "🇹🇷", baslik: "مستقل تمامًا", aciklama: "بدون استثمارات أجنبية، موثوق به من الأطباء الأتراك" },
      { ikon: "🌍", baslik: "دعم متعدد اللغات", aciklama: "دعم كامل بـ TR · EN · RU · AR · FA" },
    ],
    cta_baslik: "أنشئ ملفك الشخصي",
    cta_alt: "أنشئ ملفك المجاني وتواصل مع المزيد من المرضى.",
    cta_btn: "التسجيل المجاني",
    kayit: "التسجيل المجاني",
    giris: "تسجيل الدخول",
    populer: "الأكثر شيوعًا",
  },

  fa: {
    dir: "rtl",
    hero1: "پزشک مناسب خود را",
    hero2: "با اطمینان پیدا کنید",
    hero_alt: "نظرات تأییدشده، پروفایل‌های شفاف و نوبت‌گیری آسان.",
    uzmanlik_baslik: "تخصص را انتخاب کنید",
    uzmanlik_alt: "متخصص مناسب برای نیاز خود را بیابید",
    uzmanliklar: { "kbb-uzmani": "گوش و حلق و بینی", "kardiyoloji": "قلب", "ortopedi": "ارتوپدی", "plastik-cerrahi": "جراحی پلاستیک", "goz-hastaliklari": "چشم", "dis-hekimi": "دندانپزشک", "dermatoloji": "پوست", "noroloji": "مغز و اعصاب", "psikiyatri": "روانپزشکی", "cocuk-hastaliklari": "کودکان", "estetik-cerrahi": "جراحی زیبایی", "rinoplasti": "رینوپلاستی" },
    nasil_baslik: "چطور کار می‌کند",
    adimlar: [
      { baslik: "جستجوی پزشک", aciklama: "صدها پزشک را بر اساس تخصص و شهر فیلتر کنید" },
      { baslik: "بررسی پروفایل", aciklama: "نظرات تأییدشده و اطلاعات شفاف را بخوانید" },
      { baslik: "رزرو نوبت", aciklama: "درخواست نوبت را مستقیماً از پروفایل پزشک ارسال کنید" },
    ],
    fiyat_baslik: "پکیج‌ها و قیمت‌ها",
    fiyat_alt: "قیمت‌گذاری شفاف برای متخصصان بهداشت",
    paketler: [
      { ad: "رایگان", fiyat: "₺0", periyot: "برای همیشه", renk: "#6B7280", bg: "#F5F7FA", border: "#E5E7EB", ozellikler: ["پروفایل پایه", "درخواست نوبت", "نظرات بیماران", "آپلود عکس"], cta: "شروع رایگان", href: "/kayit-ol", populer: false },
      { ad: "پریمیوم", fiyat: "₺999", periyot: "ماه", renk: "#D97706", bg: "#FFFBEB", border: "#FDE68A", ozellikler: ["پروفایل پایه", "درخواست نوبت", "نظرات", "دستیار هوش مصنوعی", "واتس‌اپ"], cta: "ارتقا به پریمیوم", href: "mailto:satis@doktorpusula.com", populer: true },
      { ad: "پرو", fiyat: "₺1,599", periyot: "ماه", renk: "#7C3AED", bg: "#F5F3FF", border: "#DDD6FE", ozellikler: ["همه امکانات پریمیوم", "داشبورد آنالیتیک", "برجسته‌سازی", "انتشار مقاله"], cta: "ارتقا به پرو", href: "mailto:satis@doktorpusula.com", populer: false },
    ],
    neden_baslik: "چرا DoktorPusula؟",
    neden: [
      { ikon: "✅", baslik: "نظرات تأییدشده", aciklama: "هر نظر با تلفن تأیید می‌شود و قابل حذف نیست" },
      { ikon: "🇹🇷", baslik: "کاملاً مستقل", aciklama: "بدون سرمایه‌گذاری خارجی، مورد اعتماد پزشکان ترک" },
      { ikon: "🌍", baslik: "پشتیبانی چندزبانه", aciklama: "پشتیبانی کامل به TR · EN · RU · AR · FA" },
    ],
    cta_baslik: "پروفایل خود را بسازید",
    cta_alt: "پروفایل رایگان خود را بسازید و به بیماران بیشتری دسترسی پیدا کنید.",
    cta_btn: "ثبت نام رایگان",
    kayit: "ثبت نام رایگان",
    giris: "ورود",
    populer: "محبوب",
  },
};
