export const HASTALIKLAR = [
  // KBB
  { slug: "sinuzit", ad: "Sinüzit", kategori: "KBB", ikon: "👃", uzmanlik: "KBB Uzmanı", uzmanlikSlug: "kbb-uzmani", belirtiler: ["Burun tıkanıklığı", "Yüzde baskı ve ağrı", "Sarı-yeşil burun akıntısı", "Baş ağrısı", "Koku alma kaybı"], aciklama: "Sinüzit, burun boşluklarının çevresindeki hava dolu boşlukların (sinüslerin) iltihaplanmasıdır. Akut ve kronik formları bulunur.", tedavi: ["Antibiyotik tedavisi", "Burun spreyleri", "Tuzlu su ile burun yıkama", "Cerrahi (kronik vakalarda)"] },
  { slug: "bademcik-iltihaplanmasi", ad: "Bademcik İltihabı", kategori: "KBB", ikon: "🦷", uzmanlik: "KBB Uzmanı", uzmanlikSlug: "kbb-uzmani", belirtiler: ["Boğaz ağrısı", "Yutkunmada zorluk", "Ateş", "Bademciklerde beyaz lekeler", "Lenf bezi şişliği"], aciklama: "Tonsil iltihabı olarak da bilinen bademcik iltihabı, boğazın arka kısmındaki bademciklerin bakteriyel veya viral enfeksiyona bağlı iltihaplanmasıdır.", tedavi: ["Antibiyotik tedavisi", "Ağrı kesiciler", "Bol sıvı tüketimi", "Tekrarlayan vakalarda tonsillektomi"] },
  { slug: "vertigo", ad: "Vertigo", kategori: "KBB", ikon: "🌀", uzmanlik: "KBB Uzmanı", uzmanlikSlug: "kbb-uzmani", belirtiler: ["Dönme hissi", "Denge kaybı", "Bulantı ve kusma", "Göz hareketlerinde anormallik", "İşitme kaybı (bazı tiplerde)"], aciklama: "Vertigo, çevre dönermiş ya da kişinin kendisi dönüyormuş gibi hissetmesiyle karakterize bir denge bozukluğudur. Çoğunlukla iç kulak kaynaklıdır.", tedavi: ["Epley manevrası", "İlaç tedavisi (antihistaminikler)", "Vestibüler rehabilitasyon", "Altta yatan hastalığın tedavisi"] },

  // Kardiyoloji
  { slug: "hipertansiyon", ad: "Hipertansiyon (Yüksek Tansiyon)", kategori: "Kardiyoloji", ikon: "❤️", uzmanlik: "Kardiyolog", uzmanlikSlug: "kardiyoloji", belirtiler: ["Baş ağrısı (özellikle sabahları)", "Burun kanaması", "Görme bozukluğu", "Çarpıntı", "Çoğunlukla belirti vermez"], aciklama: "Hipertansiyon, kan basıncının sürekli olarak normalin üzerinde olması durumudur (≥140/90 mmHg). 'Sessiz katil' olarak bilinir çünkü genellikle belirti vermez.", tedavi: ["Tuz kısıtlaması", "Düzenli egzersiz", "Antihipertansif ilaçlar", "Stres yönetimi", "Sağlıklı beslenme"] },
  { slug: "carpinti", ad: "Çarpıntı (Aritmi)", kategori: "Kardiyoloji", ikon: "💓", uzmanlik: "Kardiyolog", uzmanlikSlug: "kardiyoloji", belirtiler: ["Hızlı veya düzensiz kalp atışı hissi", "Göğüs ağrısı", "Baş dönmesi", "Nefes darlığı", "Bayılma hissi"], aciklama: "Çarpıntı, kalp atışlarının düzensiz, çok hızlı veya çok yavaş hissedilmesidir. Benign olabildiği gibi ciddi kardiyak aritmilerin belirtisi de olabilir.", tedavi: ["EKG değerlendirmesi", "İlaç tedavisi", "Ablasyon", "Yaşam tarzı değişiklikleri"] },

  // Ortopedi
  { slug: "bel-fitigi", ad: "Bel Fıtığı", kategori: "Ortopedi", ikon: "🦴", uzmanlik: "Ortopedi Uzmanı", uzmanlikSlug: "ortopedi", belirtiler: ["Bel ve kalça ağrısı", "Bacağa yayılan ağrı (siyatik)", "Uyuşma ve karıncalanma", "Bacakta güçsüzlük", "Uzun süre oturmada zorluk"], aciklama: "Bel fıtığı, omurlar arasındaki disk adı verilen yastıkçıkların çeşitli nedenlerle şeklini bozarak sinir köklerine baskı yapması durumudur.", tedavi: ["Fizik tedavi", "Ağrı kesici ve kas gevşeticiler", "Epidural enjeksiyon", "Cerrahi (şiddetli vakalarda)"] },
  { slug: "diz-agrisi", ad: "Diz Ağrısı", kategori: "Ortopedi", ikon: "🦵", uzmanlik: "Ortopedi Uzmanı", uzmanlikSlug: "ortopedi", belirtiler: ["Diz ekleminde ağrı", "Şişlik ve kızarıklık", "Merdiven çıkmada zorluk", "Diz kapağında hareket kısıtlılığı", "Kilitleme hissi"], aciklama: "Diz ağrısı, kıkırdak yıpranması, menisküs yırtığı, bağ hasarı veya artrit gibi farklı nedenlere bağlı olabilir. Yaşla birlikte sıklığı artar.", tedavi: ["Fizik tedavi ve egzersiz", "Ağrı kesici ve anti-inflamatuarlar", "Kortikosteroid enjeksiyonu", "Artroskopi veya protez (ileri evrelerde)"] },
  { slug: "boyun-fitigi", ad: "Boyun Fıtığı", kategori: "Ortopedi", ikon: "🔄", uzmanlik: "Ortopedi Uzmanı", uzmanlikSlug: "ortopedi", belirtiler: ["Boyun ağrısı", "Omuza ve kola yayılan ağrı", "El ve parmaklarda uyuşma", "Kol güçsüzlüğü", "Baş ağrısı"], aciklama: "Boyun fıtığı, servikal omurlar arasındaki disklerin yıpranması veya çıkması sonucu sinir köklerine baskı yapmasıdır. Masa başı çalışanlarda yaygındır.", tedavi: ["Fizik tedavi", "Servikal korse", "İlaç tedavisi", "Enjeksiyon tedavileri", "Cerrahi (gerekirse)"] },

  // Dermatoloji
  { slug: "akne", ad: "Akne (Sivilce)", kategori: "Dermatoloji", ikon: "✨", uzmanlik: "Dermatolog", uzmanlikSlug: "dermatoloji", belirtiler: ["Yüz, sırt ve göğüste sivilceler", "Kapalı ve açık komedonlar", "Ağrılı nodüller", "Yağlı cilt", "İz ve lekeler"], aciklama: "Akne, yağ bezlerinin tıkanması ve bakteri üremesiyle oluşan kronik inflamatuvar bir cilt hastalığıdır. Ergenlik döneminde sık görülür ancak yetişkinleri de etkiler.", tedavi: ["Topikal retinoidler ve antibiyotikler", "Oral antibiyotik tedavisi", "Hormon tedavisi (kadınlarda)", "İzotretinoin (ağır vakalarda)", "Lazer tedavisi"] },
  { slug: "egzama", ad: "Egzama (Atopik Dermatit)", kategori: "Dermatoloji", ikon: "🌿", uzmanlik: "Dermatolog", uzmanlikSlug: "dermatoloji", belirtiler: ["Yoğun kaşıntı", "Kuru ve pullu cilt", "Kızarıklık ve şişlik", "Cilt çatlakları", "Uykusuzluğa yol açan kaşıntı"], aciklama: "Egzama, cildin enflamatuvar bir hastalığıdır. Kronik seyirli olup alerjik rinit ve astımla birlikte 'atopik triad' oluşturabilir.", tedavi: ["Nemlendiriciler ve bariyer kremler", "Kortikosteroid kremler", "Antihistaminikler", "Fototerapisi", "Biyolojik ilaçlar (şiddetli vakalarda)"] },
  { slug: "sac-dokulmesi", ad: "Saç Dökülmesi (Alopesi)", kategori: "Dermatoloji", ikon: "💆", uzmanlik: "Dermatolog", uzmanlikSlug: "dermatoloji", belirtiler: ["Aşırı saç dökülmesi", "Saçlarda incelme", "Alnın genişlemesi (erkeklerde)", "Saçlı deride leke veya yama", "Tüm vücutta kıllanma kaybı"], aciklama: "Saç dökülmesi; genetik, hormonal, stres, beslenme eksiklikleri veya otoimmün nedenlerle ortaya çıkabilir. Androgenetik alopesi en yaygın formudur.", tedavi: ["Minoksidil (topikal)", "Finasterid (oral, erkeklerde)", "PRP (Plazma zengin trombosit) tedavisi", "Saç ekimi", "Altta yatan hastalığın tedavisi"] },

  // Göz Hastalıkları
  { slug: "miyopi", ad: "Miyopi (Uzak Görememe)", kategori: "Göz Hastalıkları", ikon: "👁️", uzmanlik: "Göz Hastalıkları Uzmanı", uzmanlikSlug: "goz-hastaliklari", belirtiler: ["Uzaktaki nesneleri bulanık görme", "Gözleri kısmak zorunda kalma", "Baş ağrısı", "Göz yorgunluğu", "Gece görüşünde zorluk"], aciklama: "Miyopi, ışığın retina üzerinde değil önünde odaklanması nedeniyle uzaktaki nesnelerin bulanık görünmesidir. Genetik yatkınlık ve yakın çalışma en yaygın nedenlerdir.", tedavi: ["Gözlük veya kontak lens", "Lazer tedavisi (Lasik, PRK)", "Göz içi lens implantı"] },
  { slug: "katarakt", ad: "Katarakt", kategori: "Göz Hastalıkları", ikon: "🔍", uzmanlik: "Göz Hastalıkları Uzmanı", uzmanlikSlug: "goz-hastaliklari", belirtiler: ["Bulanık veya sisli görüş", "Işığa karşı hassasiyet", "Gece görüşünde azalma", "Renklerin soluk görünmesi", "Sık gözlük numarası değişimi"], aciklama: "Katarakt, göz merceğinin zamanla bulanıklaşmasıdır. İleri yaşta sık görülmekle birlikte konjenital veya travmatik formları da vardır.", tedavi: ["Cerrahi (fakoemülsifikasyon)", "Yapay lens (IOL) implantasyonu"] },

  // Gastroenteroloji
  { slug: "reflu", ad: "Reflü (GÖRH)", kategori: "Gastroenteroloji", ikon: "🔥", uzmanlik: "Gastroenterolog", uzmanlikSlug: "gastroenteroloji", belirtiler: ["Yanma ve ekşime hissi", "Ağıza acı su gelmesi", "Yutma güçlüğü", "Kronik öksürük", "Boğaz tahrişi"], aciklama: "Gastroözofageal reflü hastalığı (GÖRH), mide içeriğinin yemek borusuna kaçmasıyla oluşur. Yaşam tarzı ve diyet faktörleri önemli rol oynar.", tedavi: ["Proton pompası inhibitörleri", "H2 reseptör blokerleri", "Yaşam tarzı değişiklikleri (diyet, kilo)", "Cerrahi (Fundoplikasyon)"] },
  { slug: "gastrit", ad: "Gastrit", kategori: "Gastroenteroloji", ikon: "🫁", uzmanlik: "Gastroenterolog", uzmanlikSlug: "gastroenteroloji", belirtiler: ["Üst karın ağrısı", "Bulantı ve kusma", "Şişkinlik", "Yemek sonrası dolgunluk", "İştah kaybı"], aciklama: "Gastrit, mide mukozasının iltihaplanmasıdır. H. pylori bakterisi, NSAİD ilaç kullanımı ve alkol başlıca nedenler arasındadır.", tedavi: ["H. pylori eradikasyon tedavisi", "Mide asidini azaltan ilaçlar", "Diyet düzenlemeleri", "Alkol ve NSAİD'den kaçınma"] },

  // Endokrinoloji
  { slug: "diyabet", ad: "Diyabet (Şeker Hastalığı)", kategori: "Endokrinoloji", ikon: "🩸", uzmanlik: "Endokrinolog", uzmanlikSlug: "ic-hastaliklari", belirtiler: ["Aşırı susama ve sık idrara çıkma", "Yorgunluk", "Bulanık görme", "Yavaş iyileşen yaralar", "Kilo kaybı (Tip 1)"], aciklama: "Diyabet, insülin üretiminin yetersizliği veya insülin direnci nedeniyle kan şekerinin yüksek kalmasıyla karakterize metabolik bir hastalıktır.", tedavi: ["İnsülin tedavisi (Tip 1)", "Oral antidiyabetikler (Tip 2)", "Kan şekeri takibi", "Diyet ve egzersiz", "Yaşam tarzı değişiklikleri"] },
  { slug: "tiroit-hastaliklari", ad: "Tiroit Hastalıkları", kategori: "Endokrinoloji", ikon: "🦋", uzmanlik: "Endokrinolog", uzmanlikSlug: "ic-hastaliklari", belirtiler: ["Yorgunluk ve halsizlik", "Kilo değişimleri", "Çarpıntı veya yavaş nabız", "Saç dökülmesi", "Üşüme veya terleme"], aciklama: "Tiroit bezi hastalıkları; hipotiroidizm (az çalışan tiroit) ve hipertiroidizm (aşırı çalışan tiroit) başlıkları altında değerlendirilir. Hashimoto ve Graves en yaygın nedenlerdir.", tedavi: ["Tiroit hormon replasmanı (hipotiroit)", "Antitiroit ilaçlar (hipertiroit)", "Radyoaktif iyot tedavisi", "Cerrahi"] },

  // Nöroloji
  { slug: "migren", ad: "Migren", kategori: "Nöroloji", ikon: "🧠", uzmanlik: "Nörolog", uzmanlikSlug: "noroloji", belirtiler: ["Şiddetli, zonklayan baş ağrısı", "Bulantı ve kusma", "Işık ve sese aşırı duyarlılık", "Görsel aura (bazı tiplerde)", "Birkaç saat ile birkaç gün süren ataklar"], aciklama: "Migren, tekrarlayan şiddetli baş ağrısı atakları ile karakterize nörolojik bir hastalıktır. Tetikleyiciler arasında stres, uyku düzensizliği ve hormonal değişimler sayılabilir.", tedavi: ["Triptan grubu ilaçlar (atak tedavisi)", "NSAİD'ler", "Önleyici ilaç tedavisi", "Botoks enjeksiyonu (kronik migrende)", "Yaşam tarzı düzenlemeleri"] },

  // Kadın Hastalıkları
  { slug: "polikistik-over", ad: "Polikistik Over Sendromu (PCOS)", kategori: "Kadın Hastalıkları", ikon: "🌸", uzmanlik: "Kadın Doğum Uzmanı", uzmanlikSlug: "kadin-hastaliklari-ve-dogum", belirtiler: ["Düzensiz veya gecikmiş adet", "Aşırı kıllanma (hirsutizm)", "Akne", "Kilo artışı ve insülin direnci", "Kısırlık"], aciklama: "PCOS, yumurtalıklarda küçük kistlerin oluşumu ve hormon dengesizliği ile karakterize yaygın bir endokrin bozukluktur. Üreme çağındaki kadınların %10'unu etkiler.", tedavi: ["Oral kontraseptifler (adet düzenlemesi)", "Metformin (insülin direnci)", "Kilo kontrolü ve diyet", "Ovülasyon indüksiyonu (kısırlık tedavisi)"] },

  // Üroloji
  { slug: "bobrek-tasi", ad: "Böbrek Taşı", kategori: "Üroloji", ikon: "🪨", uzmanlik: "Üroloji Uzmanı", uzmanlikSlug: "uroloji", belirtiler: ["Şiddetli yan ve bel ağrısı (renal kolik)", "İdrarda kan", "Sık idrara çıkma isteği", "Bulantı ve kusma", "İdrarda yanma"], aciklama: "Böbrek taşları, idrarda çözünmüş mineral ve tuzların kristalleşmesiyle oluşur. Kalsiyum oksalat en yaygın taş tipidir. Yetersiz sıvı tüketimi önemli bir risk faktörüdür.", tedavi: ["Bol su içmek ve ağrı kontrolü (küçük taşlar)", "ESWL (vücut dışı ses dalgası litotripsi)", "Üretoroskopi", "Perkütan nefrolitotomi (büyük taşlar)"] },

  // Pediatri / KBB
  { slug: "adenoid", ad: "Geniz Eti (Adenoid)", kategori: "Pediatri / KBB", ikon: "👶", uzmanlik: "KBB Uzmanı", uzmanlikSlug: "kbb-uzmani", belirtiler: ["Ağızdan nefes alma", "Horlama ve uyku apnesi", "Sık kulak iltihabı", "Burun tıkanıklığı", "Burun sesi ile konuşma"], aciklama: "Adenoid, nazofarenkste bulunan lenf dokusunun büyümesidir. Çocukluk çağında sık görülür ve üst solunum yolu tıkanıklığına yol açabilir.", tedavi: ["Tıbbi izlem (hafif vakalarda)", "Burun spreyleri", "Adenoidektomi (cerrahi)"] },

  // Psikiyatri
  { slug: "depresyon", ad: "Depresyon", kategori: "Psikiyatri", ikon: "🌧️", uzmanlik: "Psikiyatrist", uzmanlikSlug: "psikiyatri", belirtiler: ["Sürekli üzüntü ve umutsuzluk hissi", "Enerji ve istek kaybı", "Uyku bozuklukları", "İştah değişiklikleri", "Konsantrasyon güçlüğü"], aciklama: "Depresyon, günlük yaşamı etkileyen, tedavi edilebilir bir ruh sağlığı bozukluğudur. Yaşam olayları, genetik yatkınlık ve beyin kimyası rol oynar.", tedavi: ["Antidepresan ilaç tedavisi", "Psikoterapi (BDT)", "EKT (ağır vakalarda)", "Yaşam tarzı düzenlemeleri"] },
  { slug: "anksiyete", ad: "Anksiyete Bozukluğu", kategori: "Psikiyatri", ikon: "😰", uzmanlik: "Psikiyatrist", uzmanlikSlug: "psikiyatri", belirtiler: ["Aşırı endişe ve korku", "Çarpıntı ve terleme", "Nefes darlığı", "Uyku bozukluğu", "Konsantrasyon güçlüğü"], aciklama: "Anksiyete bozuklukları, günlük yaşamı bozan yoğun ve süregelen kaygı durumlarıdır. Generalize anksiyete, panik bozukluk ve sosyal fobi başlıca türleridir.", tedavi: ["Anksiyolitik ilaçlar", "SSRI/SNRI antidepresanlar", "Bilişsel davranışçı terapi", "Gevşeme teknikleri"] },

  // Göğüs Hastalıkları
  { slug: "astim", ad: "Astım", kategori: "Göğüs Hastalıkları", ikon: "🫁", uzmanlik: "Göğüs Hastalıkları Uzmanı", uzmanlikSlug: "gogus-hastaliklari", belirtiler: ["Hırıltılı solunum", "Nefes darlığı", "Göğüste sıkışma hissi", "Özellikle gece/sabah öksürük", "Eforla artan semptomlar"], aciklama: "Astım, hava yollarının kronik inflamasyonu ve aşırı duyarlılığıyla karakterize bir solunum yolu hastalığıdır. Alerjenler, enfeksiyonlar ve egzersiz atak tetikleyicileridir.", tedavi: ["İnhaler bronkodilatörler (kısa etkili)", "İnhaler kortikosteroidler", "Uzun etkili bronkodilatörler", "Allerjen immünoterapisi"] },
];
